Repository cs361w2019-osu/sprint1-group-1868, pull requests merged in 2019-02, with the labels that each got.

#27 Update the .java structure
  src/main/java/assets/game.js
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Ship.java
Labels: feature

#43 game.js via upload
  src/main/java/assets/game.js
Labels: bug

#50 Add a title
  src/main/java/assets/game.js
Labels: feature

#57 Add the sonar pulse
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/conf/Routes.java
  src/main/java/controllers/ApplicationController.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Ship.java
  src/main/java/views/ApplicationController/index.ftl.html
Labels: feature

#60 add armor
  src/main/java/assets/game.js
  src/main/java/cs361/battleships/models/AtackStatus.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Ship.java
Labels: feature

#73 Michael
  src/main/java/assets/game.js
Labels: bug

#74 Add test files via upload
  src/test/java/cs361/battleships/models/BoardTest.java
Labels: sprint-3, test

#75 Michael
  src/test/java/cs361/battleships/models/BoardTest.java
Labels: enhancement, sprint-3
