Repository cs361w2019-osu/sprint1-group-1868, pull requests merged in 2019-03, with the labels that each got.

#86 Shile
  src/main/java/assets/game.js
  src/main/java/controllers/ApplicationController.java
  src/main/java/controllers/PlacementGameAction.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Ship.java
  src/main/java/views/ApplicationController/index.ftl.html
  src/test/java/cs361/battleships/models/BoardTest.java
Labels: feature

#95 Joeking123 (Please read comment about no need to add new cases in BoardTest)
  src/main/java/assets/game.js
  src/main/java/conf/Routes.java
  src/main/java/controllers/ApplicationController.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/views/ApplicationController/index.ftl.html
Labels: enhancement, sprint-4

#97 Update index.ftl.html
  src/main/java/views/ApplicationController/index.ftl.html
Labels: enhancement
